url: https://visibledao.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Visible DAO ·" # the name of your site, e.g. ACME Corp.

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - CNAME
  - package.json
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js